### ISSUE TITLE
MkvCage

### ISSUE THREAD

**Issue by Pireo** [hannsen/userscripts#1]
http://www.mkvcage.bid/

are you capable of writing a plugin for this? A site based on movie is lacking and this one has high quality ones.

**Comment by hannsen** [comment]
you mean a qbit plugin right?

**Comment by Pireo** [comment]
Yeah, if you have time.

**Comment by hannsen** [comment]
done 

https://github.com/hannsen/qbittorrent_search_plugins/blob/master/mkvcage.py

next time please post in the right repository
